### PR TITLE
Fix objects which will always have a room prop to not be possibly undefined

### LINKED ISSUE #99: creep.room can literally never be undefined but types say it can be
If the creep exists, it can see the room it's in. Unfortunately, the types don't reflect this and accesses without guards will cause TS errors.

### PR DESCRIPTION
**Pull request by lf-**
They can't be undefined so the types should say that.

Fixes #99

### CODE REVIEW

**Comment by lf-** [comment]
Forgot to build, oops.

**Review by Dessix — CHANGES_REQUESTED** [review]
It seems you rebuilt with the wrong encoding or line endings or something? That should not be a 2500line delta.

**Comment by lf-** [comment]
WINDOWS STAHP PLS. fixed

**Review by Dessix — APPROVED** [review]

**Comment by lf-** [comment]
I'm done, you can merge :)

**Comment by anisoptera** [comment]
I was initially a bit concerned because _others'_ owned structures don't give visibility, but you also can't have an instance of OwnedStructure that you don't have visibility to, so it's sort of a tautology.

Cool!

**Comment by lf-** [comment]
Looks like there might be a mistake here: some of the references aren't properly read only. This is partially my fault, having not known that they should be set read only.

**Comment by anisoptera** [comment]
I reverted the commit that did that (it wasn't about the read only props but about something else), so no worries. :)

**Pull request merged**
