### PR TITLE
Added pathfinder Incomplete and Cost attributes

### PR DESCRIPTION
**Pull request by Dessix**
As shown in the [Screeps API documentation](http://support.screeps.com/hc/en-us/articles/207023879-PathFinder#search).

### CODE REVIEW

**Comment by seancl** [comment]
This interface still needs to be applied as the result of the PathFinder search function, right?

**Comment by Dessix** [comment]
@seancl Nicely spotted- must have clipped it out by accident. Fixed.

**Review by seancl — APPROVED** [review]
Badly needed to bring definitions in line with the live Screeps API

**Comment by Dessix** [comment]
@ChrisKitching has this covered with #82, with better commentary now that the documentation is available. Also, their version doesn't mistype `ops` as `opts` - my bad 😊
Do not merge, closing in lieu of #82's acceptance.

**Pull request closed without merging**
